openapi: 3.2.0
info:
  title: 'SAM: Licenses Entitlements API'
  contact:
    name: Flexera
    url: https://www.flexera.com
  version: 1.7.0
servers:
- url: https://{region}.snowsoftware.io
  description: You can find your **Data region** in the **Snow Atlas settings** menu, in **License details**. Your **Data region** is on the **General information** tab. For further information, see [General information](https://docs.snowsoftware.com/snow-atlas/en/UUID-2d4ce22b-e2a9-b7b0-44b8-0ecc55c2959f.html#UUID-2d4ce22b-e2a9-b7b0-44b8-0ecc55c2959f_section-idm4543865842761633102149279789 "https://docs.snowsoftware.com/snow-atlas/en/UUID-2d4ce22b-e2a9-b7b0-44b8-0ecc55c2959f.html#UUID-2d4ce22b-e2a9-b7b0-44b8-0ecc55c2959f_section-idm4543865842761633102149279789").
  variables:
    region:
      enum:
      - westeurope
      - australiasoutheast
      - eastus2
      - uksouth
      default: westeurope
tags:
- name: Entitlements
paths:
  /api/sam/v1/licenses-entitlements:
    get:
      tags:
      - Entitlements
      summary: Get License Entitlements
      description: Returns a collection of license entitlements.
      operationId: getLicenseEntitlementCollection
      parameters:
      - name: filter
        in: query
        description: For more information on the available operators and which data types those operators work on, see [Filter API call results](https://docs.snowsoftware.io/snow-atlas-api/resources/get-started-with-apis/api-conventions#filter-api-call-results).
        schema:
          type: string
        example: filter=status -eq "active"
      - name: page_number
        in: query
        description: The page number.
        schema:
          type: integer
          default: 1
          minimum: 1
      - name: page_size
        in: query
        description: The maximum number of items in the response.
        schema:
          type: integer
          default: 100
          minimum: 1
      responses:
        '200':
          description: 'OK: Your request succeeded.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateoasCollectionOfLicenseEntitlement'
        '400':
          description: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 400
                  message: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
        '500':
          description: 'Internal Server Error: Your request failed due to an internal error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 500
                  message: The service encountered an unexpected condition that prevented it from fulfilling the request.
      security:
      - BearerAuth:
        - sam.license.r
  /api/sam/v1/licenses/entitlements/computers:
    get:
      tags:
      - Entitlements
      summary: Get Computers Applications Entitlements
      description: Returns a collection of computers and applications entitlements.
      operationId: getComputerApplicationEntitlementCollection
      parameters:
      - name: filter
        in: query
        description: For more information on the available operators and which data types those operators work on, see [Filter API call results](https://docs.snowsoftware.io/snow-atlas-api/resources/get-started-with-apis/api-conventions#filter-api-call-results).
        schema:
          type: string
        example: filter=status -eq "active"
      - name: page_number
        in: query
        description: The page number.
        schema:
          type: integer
          default: 1
          minimum: 1
      - name: page_size
        in: query
        description: The maximum number of items in the response.
        schema:
          type: integer
          default: 100
          minimum: 1
      responses:
        '200':
          description: 'OK: Your request succeeded.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateoasCollectionOfComputerApplicationEntitlement'
        '400':
          description: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 400
                  message: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
        '500':
          description: 'Internal Server Error: Your request failed due to an internal error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 500
                  message: The service encountered an unexpected condition that prevented it from fulfilling the request.
      security:
      - BearerAuth:
        - sam.license.r
  /api/sam/v1/licenses/entitlements/entitlement-states:
    get:
      tags:
      - Entitlements
      summary: Get License Entitlement States
      description: Returns a collection of entitlements states.
      operationId: getEntitlementStateCollection
      parameters:
      - name: page_number
        in: query
        description: The page number.
        schema:
          type: integer
          default: 1
          minimum: 1
      - name: page_size
        in: query
        description: The maximum number of items in the response.
        schema:
          type: integer
          default: 100
          minimum: 1
      responses:
        '200':
          description: 'OK: Your request succeeded.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateoasCollectionOfEntitlementState'
        '400':
          description: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 400
                  message: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
        '500':
          description: 'Internal Server Error: Your request failed due to an internal error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 500
                  message: The service encountered an unexpected condition that prevented it from fulfilling the request.
      security:
      - BearerAuth:
        - sam.license.r
  /api/sam/v1/licenses/entitlements/users:
    get:
      tags:
      - Entitlements
      summary: Get User License Entitlements
      description: Returns a collection of user entitlements.
      operationId: getUserApplicationEntitlementCollection
      parameters:
      - name: filter
        in: query
        description: For more information on the available operators and which data types those operators work on, see [Filter API call results](https://docs.snowsoftware.io/snow-atlas-api/resources/get-started-with-apis/api-conventions#filter-api-call-results).
        schema:
          type: string
        example: filter=status -eq "active"
      - name: page_number
        in: query
        description: The page number.
        schema:
          type: integer
          default: 1
          minimum: 1
      - name: page_size
        in: query
        description: The maximum number of items in the response.
        schema:
          type: integer
          default: 100
          minimum: 1
      responses:
        '200':
          description: 'OK: Your request succeeded.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateoasCollectionOfUserApplicationEntitlement'
        '400':
          description: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 400
                  message: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
        '500':
          description: 'Internal Server Error: Your request failed due to an internal error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 500
                  message: The service encountered an unexpected condition that prevented it from fulfilling the request.
      security:
      - BearerAuth:
        - sam.license.r
components:
  schemas:
    HateoasCollectionOfLicenseEntitlement:
      allOf:
      - $ref: '#/components/schemas/FilteredResponseOfLicenseEntitlement'
      - type: object
        additionalProperties: false
        required:
        - _links
        properties:
          _links:
            type: array
            description: A collection of links to related resources.
            items:
              $ref: '#/components/schemas/Link'
    EntitlementState:
      allOf:
      - $ref: '#/components/schemas/HateoasResource'
      - type: object
        additionalProperties: false
        properties:
          id:
            type: string
            description: The unique ID of the entitlement state.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          name:
            type:
            - string
            - 'null'
            description: The name of the entitlement state.
            example: Partially covered
          description:
            type:
            - string
            - 'null'
            description: The description of the entitlement state.
            example: The virtual machine is licensed by the host it is running on.
    Error:
      description: The error details.
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
          description: The HTTP status code.
        message:
          type: string
          description: The error message.
    Link:
      type: object
      description: Represents a hypermedia link referenced from a IResource, according to HATEOAS.
      additionalProperties: false
      properties:
        href:
          type:
          - string
          - 'null'
          description: The associated relative URL.
          example: /api/custom-fields/v1/custom-fields
        rel:
          type:
          - string
          - 'null'
          description: Specifies the relationship between the current document and the linked document/resource.
          example: self
        method:
          type:
          - string
          - 'null'
          description: The method to access related resources.
          example: GET
    ComputerApplicationEntitlement:
      allOf:
      - $ref: '#/components/schemas/HateoasResource'
      - type: object
        additionalProperties: false
        properties:
          computerId:
            type: string
            description: The unique ID of the computer.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          applicationId:
            type: string
            description: The unique ID of the application.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          metricId:
            type: string
            description: The unique ID of the metric.
            format: guid
            example: 5891a1d8-7fb0-45bd-b1f6-01c943f9c572
          entitlementStateId:
            type: string
            description: The unique ID of the entitlement state.
            format: guid
            example: 6fb32edf-1d45-44e3-a55d-6df6068c0c08
    AssignmentType:
      type: string
      description: The assignment type.
      x-enumNames:
      - Organization
      - Computer
      - User
      - Site
      enum:
      - Organization
      - Computer
      - User
      - Site
    FilteredResponseOfUserApplicationEntitlement:
      type: object
      description: Filtered response.
      additionalProperties: false
      required:
      - items
      - pagination
      properties:
        items:
          type: array
          description: A collection of items.
          items:
            $ref: '#/components/schemas/UserApplicationEntitlement'
        pagination:
          description: The pagination details.
          oneOf:
          - $ref: '#/components/schemas/Pagination'
    Pagination:
      type: object
      description: The pagination details.
      additionalProperties: false
      required:
      - page_size
      - page_number
      properties:
        page_size:
          type: integer
          description: The page size you requested.
          format: int32
          example: 25
        page_number:
          type: integer
          description: The page number you requested.
          format: int32
          example: 1
        total_pages:
          type:
          - integer
          - 'null'
          description: The total number of pages.
          format: int32
          example: 5
        total_items:
          type:
          - integer
          - 'null'
          description: The total number of items.
          format: int32
          example: 100
    HateoasCollectionOfUserApplicationEntitlement:
      allOf:
      - $ref: '#/components/schemas/FilteredResponseOfUserApplicationEntitlement'
      - type: object
        additionalProperties: false
        required:
        - _links
        properties:
          _links:
            type: array
            description: A collection of links to related resources.
            items:
              $ref: '#/components/schemas/Link'
    UserApplicationEntitlement:
      allOf:
      - $ref: '#/components/schemas/HateoasResource'
      - type: object
        additionalProperties: false
        properties:
          userId:
            type: string
            description: The unique ID of the user.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          applicationId:
            type: string
            description: The unique ID of the application.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          metricId:
            type: string
            description: The unique ID of the metric.
            format: guid
            example: 5891a1d8-7fb0-45bd-b1f6-01c943f9c572
          entitlementStateId:
            type: string
            description: The unique ID of the entitlement state.
            format: guid
            example: 6fb32edf-1d45-44e3-a55d-6df6068c0c08
    HateoasCollectionOfEntitlementState:
      allOf:
      - $ref: '#/components/schemas/FilteredResponseOfEntitlementState'
      - type: object
        additionalProperties: false
        required:
        - _links
        properties:
          _links:
            type: array
            description: A collection of links to related resources.
            items:
              $ref: '#/components/schemas/Link'
    FilteredResponseOfComputerApplicationEntitlement:
      type: object
      description: Filtered response.
      additionalProperties: false
      required:
      - items
      - pagination
      properties:
        items:
          type: array
          description: A collection of items.
          items:
            $ref: '#/components/schemas/ComputerApplicationEntitlement'
        pagination:
          description: The pagination details.
          oneOf:
          - $ref: '#/components/schemas/Pagination'
    HateoasResource:
      type: object
      additionalProperties: false
      required:
      - _links
      properties:
        _links:
          type: array
          description: A collection of links to related resources.
          items:
            $ref: '#/components/schemas/Link'
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    FilteredResponseOfEntitlementState:
      type: object
      description: Filtered response.
      additionalProperties: false
      required:
      - items
      - pagination
      properties:
        items:
          type: array
          description: A collection of items.
          items:
            $ref: '#/components/schemas/EntitlementState'
        pagination:
          description: The pagination details.
          oneOf:
          - $ref: '#/components/schemas/Pagination'
    HateoasCollectionOfComputerApplicationEntitlement:
      allOf:
      - $ref: '#/components/schemas/FilteredResponseOfComputerApplicationEntitlement'
      - type: object
        additionalProperties: false
        required:
        - _links
        properties:
          _links:
            type: array
            description: A collection of links to related resources.
            items:
              $ref: '#/components/schemas/Link'
    FilteredResponseOfLicenseEntitlement:
      type: object
      description: Filtered response.
      additionalProperties: false
      required:
      - items
      - pagination
      properties:
        items:
          type: array
          description: A collection of items.
          items:
            $ref: '#/components/schemas/LicenseEntitlement'
        pagination:
          description: The pagination details.
          oneOf:
          - $ref: '#/components/schemas/Pagination'
    LicenseEntitlement:
      allOf:
      - $ref: '#/components/schemas/HateoasResource'
      - type: object
        description: The license entitlement.
        additionalProperties: false
        properties:
          applicationId:
            type: string
            description: The unique ID of the application.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          organizationId:
            type: string
            description: The unique ID of the organization.
            format: guid
            example: 49cdd99f-bc16-40f9-ad40-48f12182fb30
          metricId:
            type: string
            description: The unique ID of the metric.
            format: guid
            example: 5891a1d8-7fb0-45bd-b1f6-01c943f9c572
          assignmentType:
            description: The assignment type.
            example: Organization
            oneOf:
            - $ref: '#/components/schemas/AssignmentType'
          quantity:
            type: integer
            description: The quantity.
            format: int32
            example: 1
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
