openapi: 3.0.3
info:
  title: 'SAM: Computers Applications Computer display adapter API'
  description: API for interacting with computers.
  contact:
    name: Flexera
    url: https://www.flexera.com
  version: 1.0.0
servers:
- url: https://{region}.snowsoftware.io
  variables:
    region:
      enum:
      - westeurope
      - australiasoutheast
      - eastus2
      - uksouth
      default: westeurope
tags:
- name: Computer display adapter
paths:
  /api/sam/estate/v1/computers/{id}/hardware/displayadapters:
    get:
      tags:
      - Computer display adapter
      summary: Get Computer's Display Adapters
      description: Returns a collection of display adapters for the given computer.
      operationId: getComputerDisplayAdapters
      parameters:
      - name: id
        in: path
        required: true
        description: The unique ID of the computer.
        schema:
          type: string
      - name: page_number
        in: query
        description: The page number.
        schema:
          type: integer
          default: 1
          minimum: 1.0
      - name: page_size
        in: query
        description: The maximum number of items in the response.
        schema:
          type: integer
          default: 100
          minimum: 1.0
      - name: filter
        in: query
        description: 'The fields which you can use to filter the results. Format of the query string parameter:

          ```

          ?filter=<filter name> <operator> <value>

          ```

          Filter name | Description | Data type | Example

          :--- | --- | --- | ---


          For more information on the available operators and which data types those operators work on, see [Filter API call results](https://docs.snowsoftware.io/snow-atlas-api/resources/get-started-with-apis/api-conventions#filter-api-call-results).

          '
        schema:
          type: string
      responses:
        '200':
          description: 'OK: Your request succeeded.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerDisplayAdapter'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      security:
      - BearerAuth:
        - sam.computer.r
components:
  schemas:
    ComputerDisplayAdapter:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - type: object
        description: Response representing display adapter of a computer.
        additionalProperties: false
        required:
        - computerId
        properties:
          computerId:
            type: string
            description: The unique ID of the computer.
            format: guid
            example: 66a6b2b7-2ff1-403f-add3-60ed14a0233a
          name:
            type: string
            description: The name of the display adapter.
            nullable: true
            example: NVIDIA T1200 Laptop GPU
          currentResolution:
            type: string
            description: The current resolution of the computer's display adapter.
            nullable: true
            example: 1920 x 1200
          maxResolution:
            type: string
            description: The maximum resolution of the computer's display adapter.
            nullable: true
            example: 2560x1440
          isUpdated:
            type: boolean
            description: '```true``` if the display adapter is updated; otherwise, ```false```.'
            example: true
    Link:
      type: object
      required:
      - href
      - rel
      - method
      properties:
        href:
          type: string
          description: The associated relative URL.
          example: api/computers/v1/...
        rel:
          type: string
          description: Specifies the relationship between the current document and the linked document/resource.
          example: self
        method:
          type: string
          description: The method to access related resources.
          example: GET
    ErrorResponse:
      type: object
      description: Response representing error.
      additionalProperties: false
      required:
      - error
      properties:
        error:
          description: The error details.
          oneOf:
          - $ref: '#/components/schemas/ErrorContent'
    ErrorContent:
      type: object
      description: Details of error.
      additionalProperties: false
      required:
      - code
      - message
      properties:
        code:
          type: integer
          description: Http error code.
          format: int32
          example: 400
        message:
          type: string
          description: Additional error message.
          nullable: true
          example: 'Invalid GUID format: 123. All computer IDs must be in valid GUID format (00000000-0000-0000-0000-000000000000).'
    BaseResponse:
      type: object
      description: Base response class.
      additionalProperties: false
      required:
      - _links
      properties:
        _links:
          type: array
          description: A collection of links to related resources.
          items:
            $ref: '#/components/schemas/Link'
  responses:
    '500':
      description: 'Internal Server Error: Your request failed due to an internal error.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: 500
              message: The service encountered an unexpected condition that prevented it from fulfilling the request.
    '400':
      description: 'Bad Request: Your request is invalid or improperly formed. Consequently, the API server could not understand your request.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: 400
              message: Filter field name needs to be formatted as a string.
    '404':
      description: 'Not Found: The operation you requested failed because a resource associated with your request could not be found.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: 404
              message: Resource with ID '32aeda0a-80dc-475a-907f-2d250a3a8614' not found.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
